---
- name: Pull and deploy container from github
  hosts: production
  become_user: root
  become: true
  tasks:
  - name: run container, PORT 9090 running the container
    command: docker run -d -p 9090:8080 shub8050/myapp:1.0
